### ISSUE TITLE
Figure out Firebase backend schema/organization

### ISSUE THREAD

**Issue by io-reyes** [qtmdev/AndroidInference#4]
Either get the credentials for the existing Firebase backend, or figure out how it's organized and set up a new instance of it that's identically configured

**Comment by io-reyes** [comment]
Firebase backend appears to be in "dev" mode where anonymous read/write is allowed. Will need to figure out how to do this more securely before Amazon Mechanical Turk deployment.

**Comment by safi-manar** [comment]
Possible Solutions:
1. Give universal write-only access. Only authorized users on Firebase frontend would be able to access the data. **Concerns:** Some user could deliberately write false data to Firebase
2. Hardcode a login that all users share, so that only users using the app properly would be able to log to the Firebase. **Concerns:**  Explore Firebase documentation to see how this can be done.

**Comment by mvc-us** [comment]
Firebase got deprecated at Google IO, so apps should be moving to the firebase console on Google Cloud platform. We should take this chance to migrate over.

**Comment by io-reyes** [comment]
@qtmdev We're using Firebase on Google Cloud Platform now (https://firebase.google.com)
